# permissions for end users to edit tunnelconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunnelconfiguration-editor-role
rules:
- apiGroups:
  - cloudflared.cloudflare.com
  resources:
  - tunnelconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflared.cloudflare.com
  resources:
  - tunnelconfigurations/status
  verbs:
  - get
